# -*- coding: utf-8 -*-
"""ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahhgM0MFJA7LSOPEj0o9BgwH2ych-DGB
"""

import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
import scipy.spatial

pulsar_set = pd.read_csv('report.csv')
workSet = pulsar_set[pulsar_set['TARGET'] == 0][pulsar_set['MIP'] >= 94.6640625][pulsar_set['MIP'] <= 95.2890625]
workSetTwo = pulsar_set[pulsar_set['TARGET'] == 1][pulsar_set['MIP'] >= 52.9296875][pulsar_set['MIP'] <= 58.7890625]
new_df = pd.concat([workSet, workSetTwo])
new_df['MIP'].mean()
new_df = new_df.drop('TARGET', axis=1)
new_df

scaler = MinMaxScaler()
nnndf = scaler.fit_transform(new_df)
ans = nnndf[:, 0].mean()
print("%.3f" % (ans))
samp = [[0.089, 0.122, 0.511, 0.237, 0.445, 0.513, 0.068, 0.857]]
df = pd.DataFrame(samp)
#df
D2 = scipy.spatial.distance.cdist(nnndf,samp,'euclidean')
D2.min()